import { collection, doc, onSnapshot, runTransaction, serverTimestamp, type DocumentData, type QueryDocumentSnapshot, type QuerySnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import { drinkShoppingFingerprint } from "@/features/easydrinks/domain/pantry";

export const DRINK_SHOPPING_SCHEMA_VERSION = "easydrinks-shopping-v1";
export type DrinkShoppingHandoffRecord = { id: string; ownerId: string; schemaVersion: typeof DRINK_SHOPPING_SCHEMA_VERSION; drinkId: string; drinkName: string; canonicalIngredients: string[]; taskId: string; createdAt: Date | null; };
function toDate(value: unknown) { if (!value) return null; if (value instanceof Date) return value; if (typeof (value as { toDate?: () => Date; }).toDate === "function") return (value as { toDate: () => Date; }).toDate(); return null; }
function normalize(snapshot: QueryDocumentSnapshot<DocumentData>): DrinkShoppingHandoffRecord { const data = snapshot.data(); return { id: snapshot.id, ownerId: typeof data.ownerId === "string" ? data.ownerId : "", schemaVersion: DRINK_SHOPPING_SCHEMA_VERSION, drinkId: typeof data.drinkId === "string" ? data.drinkId : "", drinkName: typeof data.drinkName === "string" ? data.drinkName : "", canonicalIngredients: Array.isArray(data.canonicalIngredients) ? data.canonicalIngredients.filter((item: unknown): item is string => typeof item === "string") : [], taskId: typeof data.taskId === "string" ? data.taskId : "", createdAt: toDate(data.createdAt) }; }
export function subscribeToDrinkShoppingHandoffs(userId: string, callback: (records: DrinkShoppingHandoffRecord[]) => void, onError?: (error: Error) => void) { return onSnapshot(collection(db, "users", userId, "drinkShoppingHandoffs"), (snapshot: QuerySnapshot<DocumentData>) => callback(snapshot.docs.map(normalize).sort((a, b) => (b.createdAt?.getTime() || 0) - (a.createdAt?.getTime() || 0))), (error) => onError?.(error)); }
export async function createDrinkShoppingHandoff(userId: string, input: { drinkId: string; drinkName: string; ingredients: Array<{ name: string; canonicalName: string; }>; }) { const unique = [...new Map(input.ingredients.map((ingredient) => [ingredient.canonicalName, ingredient])).values()].sort((a, b) => a.canonicalName.localeCompare(b.canonicalName)); if (!unique.length) throw new Error("Choose at least one ingredient for the shopping handoff."); const id = drinkShoppingFingerprint(input.drinkId, unique.map((ingredient) => ingredient.canonicalName)); const taskRef = doc(db, "users", userId, "tasks", id); const handoffRef = doc(db, "users", userId, "drinkShoppingHandoffs", id); await runTransaction(db, async (transaction) => { if ((await transaction.get(handoffRef)).exists()) return; transaction.set(taskRef, { itemKind: "task", title: `Shop for ${input.drinkName}`.slice(0, 300), notes: `Created from EasyDrinks recipe ${input.drinkName} (${input.drinkId}).\n${unique.map((ingredient) => `- ${ingredient.name}`).join("\n")}`.slice(0, 20_000), listName: "Main", category: "Shopping", estimatedLength: "", priorityTier: 5, priorityLabel: "", dueDate: null, linkedCalendarEventId: null, linkedNoteId: null, recurring: false, completed: false, completedAt: null, deletedAt: null, linkedCalendarBlockIds: [], createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); transaction.set(handoffRef, { ownerId: userId, schemaVersion: DRINK_SHOPPING_SCHEMA_VERSION, drinkId: input.drinkId, drinkName: input.drinkName.slice(0, 300), canonicalIngredients: unique.map((ingredient) => ingredient.canonicalName), taskId: id, createdAt: serverTimestamp() }); }); return id; }
