import { collection, doc, onSnapshot, runTransaction, serverTimestamp, type DocumentData, type QueryDocumentSnapshot, type QuerySnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import type { GameDifficulty, GameMode } from "@/features/easygames/domain/gameContracts";
import type { GameId } from "@/lib/firestore/gameStats";

export const GAME_SESSION_SCHEMA_VERSION = "easygames-session-v1";
export const GAME_SCORE_FORMULA_VERSION = "easygames-score-v2";
export type GameSessionRecord = { id: string; ownerId: string; schemaVersion: typeof GAME_SESSION_SCHEMA_VERSION; formulaVersion: typeof GAME_SCORE_FORMULA_VERSION; gameId: GameId; difficulty: GameDifficulty; mode: GameMode; dateKey: string | null; challengeKey: string | null; generatorVersion: string; seed: number; puzzleSpec: Record<string, unknown>; completed: boolean; score: number; moves: number; pairs: number | null; goalsCollected: number | null; totalGoals: number | null; movesRemaining: number | null; startedAt: Date | null; completedAt: Date | null; createdAt: Date | null; };
export type GameSessionDraft = Omit<GameSessionRecord, "id" | "ownerId" | "schemaVersion" | "formulaVersion" | "createdAt" | "startedAt" | "completedAt"> & { sessionId: string; startedAt: string; completedAt: string; };
function toDate(value: unknown) { if (!value) return null; if (value instanceof Date) return value; if (typeof (value as { toDate?: () => Date; }).toDate === "function") return (value as { toDate: () => Date; }).toDate(); const parsed = new Date(String(value)); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function normalize(snapshot: QueryDocumentSnapshot<DocumentData>): GameSessionRecord { const data = snapshot.data(); return { id: snapshot.id, ownerId: typeof data.ownerId === "string" ? data.ownerId : "", schemaVersion: GAME_SESSION_SCHEMA_VERSION, formulaVersion: GAME_SCORE_FORMULA_VERSION, gameId: data.gameId, difficulty: data.difficulty, mode: data.mode, dateKey: typeof data.dateKey === "string" ? data.dateKey : null, challengeKey: typeof data.challengeKey === "string" ? data.challengeKey : null, generatorVersion: typeof data.generatorVersion === "string" ? data.generatorVersion : "", seed: Number(data.seed) >>> 0, puzzleSpec: data.puzzleSpec && typeof data.puzzleSpec === "object" ? data.puzzleSpec : {}, completed: Boolean(data.completed), score: Number.isInteger(data.score) ? data.score : 0, moves: Number.isInteger(data.moves) ? data.moves : 0, pairs: Number.isInteger(data.pairs) ? data.pairs : null, goalsCollected: Number.isInteger(data.goalsCollected) ? data.goalsCollected : null, totalGoals: Number.isInteger(data.totalGoals) ? data.totalGoals : null, movesRemaining: Number.isInteger(data.movesRemaining) ? data.movesRemaining : null, startedAt: toDate(data.startedAt), completedAt: toDate(data.completedAt), createdAt: toDate(data.createdAt) }; }
function sessionsCollection(userId: string) { return collection(db, "users", userId, "gameSessions"); }
export function subscribeToGameSessions(userId: string, callback: (records: GameSessionRecord[]) => void, onError?: (error: Error) => void) { return onSnapshot(sessionsCollection(userId), (snapshot: QuerySnapshot<DocumentData>) => callback(snapshot.docs.map(normalize).sort((a, b) => (b.completedAt?.getTime() || 0) - (a.completedAt?.getTime() || 0) || b.id.localeCompare(a.id))), (error) => onError?.(error)); }
export async function syncGameSession(userId: string, draft: GameSessionDraft) { const reference = doc(db, "users", userId, "gameSessions", draft.sessionId); await runTransaction(db, async (transaction) => { if ((await transaction.get(reference)).exists()) return; const { sessionId: _sessionId, ...record } = draft; transaction.set(reference, { ...record, ownerId: userId, schemaVersion: GAME_SESSION_SCHEMA_VERSION, formulaVersion: GAME_SCORE_FORMULA_VERSION, startedAt: new Date(draft.startedAt), completedAt: new Date(draft.completedAt), createdAt: serverTimestamp() }); }); }
