import { useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import { Link, useLocation } from "react-router-dom";
import { PageSection } from "@/components/ui/PageSection";
import { withReviewMode } from "@/features/coreloop/demo/reviewRoute";
import { useEasyGames } from "@/features/easygames/EasyGamesContext";
import { activeGameKey, canReplaceActiveGame, clearActiveGame, loadActiveGame, saveActiveGame, shouldAcceptRemoteGame, type GameSlot } from "@/features/easygames/domain/activeGameStorage";
import { deriveGameStats } from "@/features/easygames/domain/gameAnalytics";
import { dailyChallenge, difficultyLabels, gameDifficulties, gameModes, modeLabels, utcDateKey, type GameDifficulty, type GameMode } from "@/features/easygames/domain/gameContracts";
import { createTrailScout, isTrailScoutState, moveTrailScout, pauseTrailScout, trailScoutScore, type TrailDirection, type TrailScoutState } from "@/features/easygames/domain/trailScout";

const directionKeys: Record<string, TrailDirection> = { ArrowUp: "up", w: "up", ArrowRight: "right", d: "right", ArrowDown: "down", s: "down", ArrowLeft: "left", a: "left" };
function newTrailState(slot: GameSlot) { const challenge = slot.mode === "daily" ? dailyChallenge("trail-scout", slot.difficulty, new Date(`${slot.dateKey}T12:00:00Z`)) : null; return createTrailScout(challenge?.seed || Date.now(), { difficulty: slot.difficulty, mode: slot.mode, dateKey: challenge?.dateKey || null, challengeKey: challenge?.challengeKey || null }); }

export function TrailScoutPage() {
  const location = useLocation(); const { userKey, finishSession, sessions } = useEasyGames(); const [difficulty, setDifficulty] = useState<GameDifficulty>("standard"); const [mode, setMode] = useState<GameMode>("free"); const dateKey = utcDateKey();
  const slot = useMemo<GameSlot>(() => ({ gameId: "trail-scout", mode, difficulty, dateKey: mode === "daily" ? dateKey : null }), [dateKey, difficulty, mode]); const [state, setState] = useState<TrailScoutState>(() => loadActiveGame(localStorage, userKey, slot, isTrailScoutState) || newTrailState(slot)); const [liveMessage, setLiveMessage] = useState("Use the direction controls to find every trail light."); const [syncMessage, setSyncMessage] = useState(""); const [saveAttempt, setSaveAttempt] = useState(0); const completedRef = useRef(new Set<string>());
  const score = trailScoutScore(state); const gameStats = deriveGameStats(sessions, "trail-scout", difficulty);
  useEffect(() => { setState(loadActiveGame(localStorage, userKey, slot, isTrailScoutState) || newTrailState(slot)); setLiveMessage("Use the direction controls to find every trail light."); }, [slot, userKey]);
  useEffect(() => { if (state.status === "won" || state.status === "lost") return; if (!saveActiveGame(localStorage, userKey, slot, state)) setSyncMessage("Progress could not be saved on this device. Keep this tab open."); }, [slot, state, userKey]);
  useEffect(() => {
    if ((state.status !== "won" && state.status !== "lost") || completedRef.current.has(state.sessionId)) return;
    completedRef.current.add(state.sessionId);
    const completedAt = new Date().toISOString();
    void finishSession({ sessionId: state.sessionId, gameId: "trail-scout", difficulty: state.difficulty, mode: state.mode, dateKey: state.dateKey, challengeKey: state.challengeKey, generatorVersion: state.generatorVersion, seed: state.seed, puzzleSpec: { size: state.size, rocks: state.rocks, goals: state.initialGoals }, completed: state.status === "won", score, moves: state.moves, pairs: null, goalsCollected: state.collected, totalGoals: state.totalGoals, movesRemaining: state.movesRemaining, startedAt: state.startedAt, completedAt })
      .then(() => { clearActiveGame(localStorage, userKey, slot); setSyncMessage("Result saved on this device and queued for private sync."); })
      .catch(() => { completedRef.current.delete(state.sessionId); setSyncMessage("Result not saved on this device. Keep this tab open, allow local storage, then retry."); });
  }, [finishSession, saveAttempt, score, slot, state, userKey]);
  useEffect(() => { const key = activeGameKey(userKey, slot); const handleStorage = (event: StorageEvent) => { if (event.key !== key || !event.newValue) return; try { const incoming: unknown = JSON.parse(event.newValue); if (isTrailScoutState(incoming)) setState((current) => shouldAcceptRemoteGame(current, incoming) ? incoming : current); setSyncMessage("Another tab advanced this trail; the newer valid state is shown."); } catch { /* ignore corrupt cross-tab state */ } }; window.addEventListener("storage", handleStorage); return () => window.removeEventListener("storage", handleStorage); }, [slot, userKey]);
  useEffect(() => { const pauseHidden = () => { if (document.hidden) setState((current) => current.status === "playing" ? pauseTrailScout(current) : current); }; document.addEventListener("visibilitychange", pauseHidden); return () => document.removeEventListener("visibilitychange", pauseHidden); }, []);

  function move(direction: TrailDirection) { setState((current) => { const next = moveTrailScout(current, direction); if (next === current) setLiveMessage("That direction is blocked or outside the trail."); else if (next.collected > current.collected) setLiveMessage("Trail light found."); else setLiveMessage(`${next.goals.length} trail light${next.goals.length === 1 ? "" : "s"} still to find.`); return next; }); }
  function restart() { if (!canReplaceActiveGame(state, () => window.confirm(mode === "daily" ? "Restart today's same Trail Scout board? Your current progress will be replaced." : "Start a new trail? Your current progress will be replaced."))) return; setState(mode === "daily" ? newTrailState(slot) : createTrailScout(Date.now(), { difficulty, mode })); setLiveMessage("New trail ready."); }
  function changeSlot(nextMode: GameMode, nextDifficulty: GameDifficulty) { if (nextMode === mode && nextDifficulty === difficulty) return; if (!canReplaceActiveGame(state, () => window.confirm("Change Trail Scout mode or difficulty? Your current progress will be replaced."))) return; const nextSlot: GameSlot = { gameId: "trail-scout", mode: nextMode, difficulty: nextDifficulty, dateKey: nextMode === "daily" ? dateKey : null }; setMode(nextMode); setDifficulty(nextDifficulty); setState(loadActiveGame(localStorage, userKey, nextSlot, isTrailScoutState) || newTrailState(nextSlot)); setLiveMessage("Selected trail ready."); }
  function handleKey(event: KeyboardEvent<HTMLDivElement>) { if (event.ctrlKey || event.metaKey || event.altKey) return; const direction = directionKeys[event.key] || directionKeys[event.key.toLocaleLowerCase()]; if (direction) { event.preventDefault(); move(direction); } if (event.key.toLocaleLowerCase() === "p") { event.preventDefault(); setState((current) => pauseTrailScout(current)); } }

  const saveFailed = syncMessage.startsWith("Result not saved");

  return (
    <PageSection eyebrow="EasyGames · Pathfinding" title="Trail Scout" description={`Collect ${state.totalGoals} trail lights on a ${state.size}×${state.size} ${difficultyLabels[difficulty]} board before ${state.movesRemaining + state.moves} moves run out.`} headingLevel={1}>
      {!sessions.some((record) => record.gameId === "trail-scout") ? <aside className="game-onboarding"><strong>First trail?</strong><p>Move one square at a time. Stones block movement; collect every light before the move budget reaches zero.</p></aside> : null}
      <div className="game-mode-panel"><label className="field-stack"><span>Mode</span><select value={mode} onChange={(event) => changeSlot(event.target.value as GameMode, difficulty)}>{gameModes.map((item) => <option key={item} value={item}>{modeLabels[item]}</option>)}</select></label><label className="field-stack"><span>Difficulty</span><select value={difficulty} onChange={(event) => changeSlot(mode, event.target.value as GameDifficulty)}>{gameDifficulties.map((item) => <option key={item} value={item}>{difficultyLabels[item]}</option>)}</select></label>{mode === "daily" ? <p><strong>UTC daily:</strong> {dateKey}. Restarting keeps this exact board.</p> : <p>Free play makes a fresh validated board after confirmation.</p>}</div>
      <div className="game-toolbar"><Link className="ghost-button compact-button" to={withReviewMode("/app/easygames", location.search)}>Game shelf</Link><div className="game-stat-strip"><span><strong>{state.movesRemaining}</strong> moves left</span><span><strong>{state.collected}</strong> / {state.totalGoals} lights</span><span><strong>{gameStats.bestScore}</strong> v2 best</span></div><div className="button-row"><button type="button" className="button-secondary compact-button" disabled={state.status === "won" || state.status === "lost"} onClick={() => setState((current) => pauseTrailScout(current))}>{state.status === "paused" ? "Resume" : "Pause"}</button><button type="button" className="button-secondary compact-button" onClick={restart}>{mode === "daily" ? "Restart daily" : "New trail"}</button></div></div>
      <details className="game-instructions"><summary>Rules, controls, and scoring</summary><p>Use the on-screen direction pad, or focus the board and use arrow keys/WASD. Press P to pause. Each light is 250 points; a finish adds 250 plus 20 per remaining move, with a completed difficulty bonus of {difficulty === "easy" ? 0 : difficulty === "standard" ? 75 : 150}. Time never changes the score.</p></details>
      <div className="trail-game-shell"><div className={`trail-board${state.status === "paused" ? " is-paused" : ""}`} role="grid" tabIndex={0} onKeyDown={handleKey} aria-label={`Trail board, ${state.goals.length} lights remaining. Arrow and WASD shortcuts are active while focused.`} style={{ gridTemplateColumns: `repeat(${state.size}, 1fr)` }}>{Array.from({ length: state.size * state.size }, (_, index) => { const kind = index === state.player ? "scout" : state.rocks.includes(index) ? "stone" : state.goals.includes(index) ? "light" : "path"; return <span key={index} role="gridcell" className={`trail-cell trail-cell-${kind}`} aria-label={`Row ${Math.floor(index / state.size) + 1}, column ${(index % state.size) + 1}: ${kind}`}><span aria-hidden="true">{kind === "scout" ? "▲" : kind === "stone" ? "◆" : kind === "light" ? "✦" : ""}</span></span>; })}{state.status === "paused" ? <div className="game-pause-overlay" role="status"><strong>Trail paused</strong><button type="button" className="button-primary" onClick={() => setState((current) => pauseTrailScout(current))}>Resume</button></div> : null}</div><div className="trail-controls" aria-label="Trail movement controls"><button type="button" disabled={state.status !== "playing"} onClick={() => move("up")} aria-label="Move up">↑</button><button type="button" disabled={state.status !== "playing"} onClick={() => move("left")} aria-label="Move left">←</button><button type="button" disabled={state.status !== "playing"} onClick={() => move("down")} aria-label="Move down">↓</button><button type="button" disabled={state.status !== "playing"} onClick={() => move("right")} aria-label="Move right">→</button></div></div>
      {state.status === "won" || state.status === "lost" ? <div className="game-result" role="status"><p className="eyebrow">{state.status === "won" ? "Trail complete" : "Trail ended"}</p><h2>{score} points</h2><p>{state.status === "won" ? `All lights found with ${state.movesRemaining} moves left.` : `You found ${state.collected} of ${state.totalGoals} lights.`} {syncMessage}</p><button type="button" className="button-primary" disabled={saveFailed} onClick={restart}>{mode === "daily" ? "Replay same daily" : "Start a new trail"}</button>{saveFailed ? <button type="button" className="button-secondary" onClick={() => setSaveAttempt((attempt) => attempt + 1)}>Retry saving result</button> : null}</div> : <p className="game-live-message" aria-live="polite">{liveMessage} {syncMessage}</p>}
    </PageSection>
  );
}
