import { useMemo, useState, type FormEvent } from "react";
import { Link, useLocation } from "react-router-dom";
import { PageSection } from "@/components/ui/PageSection";
import { useAuth } from "@/features/auth/AuthContext";
import { withReviewMode } from "@/features/coreloop/demo/reviewRoute";
import { useEasyDrinks } from "@/features/easydrinks/EasyDrinksContext";
import { derivePreparationStats } from "@/features/easydrinks/domain/preparation";
import { rankDrinksForPantry, shoppingIngredients } from "@/features/easydrinks/domain/pantry";
import { drinkTypeLabels, emptyDrinkDraft, filterDrinks } from "@/features/easydrinks/domain/drinks";
import { drinkTypes, type DrinkDraft, type DrinkType } from "@/lib/firestore/drinks";

export function EasyDrinksPage() {
  const { isDemoMode } = useAuth();
  const location = useLocation();
  const { drinks, pantry, preparations, isLoading, error, addDrink, saveDrink, copyDrink, addPantryItem, savePantryItem, removePantryItem, undoPreparation, sendToShopping } = useEasyDrinks();
  const [quickDraft, setQuickDraft] = useState<DrinkDraft>(emptyDrinkDraft());
  const [pantryName, setPantryName] = useState("");
  const [pantryStatus, setPantryStatus] = useState<"available" | "unavailable">("available");
  const [query, setQuery] = useState("");
  const [type, setType] = useState<DrinkType | "all">("all");
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const [minimumRating, setMinimumRating] = useState(0);
  const [matchTier, setMatchTier] = useState<"all" | "ready" | "almost">("all");
  const [message, setMessage] = useState("");
  const filtered = useMemo(() => filterDrinks(drinks, { query, type, favoritesOnly, minimumRating }), [drinks, favoritesOnly, minimumRating, query, type]);
  const matches = useMemo(() => rankDrinksForPantry(filtered, pantry).filter((match) => matchTier === "all" || match.tier === matchTier), [filtered, pantry, matchTier]);
  const stats = useMemo(() => derivePreparationStats(preparations, new Set(drinks.filter((drink) => drink.favorite).map((drink) => drink.id))), [drinks, preparations]);

  async function handleQuickCapture(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); if (!quickDraft.name.trim()) return; try { await addDrink(quickDraft); setQuickDraft(emptyDrinkDraft()); setMessage(isDemoMode ? "Added to this synthetic demo only." : "Drink saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "The drink could not be saved."); } }
  async function handlePantryAdd(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { await addPantryItem({ name: pantryName, status: pantryStatus, note: "" }); setPantryName(""); setMessage(isDemoMode ? "Synthetic pantry updated for this demo only." : "Pantry ingredient saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Pantry ingredient could not be saved."); } }

  return (
    <PageSection eyebrow="EasyDrinks" title="Make something from what you have" description="Keep a small pantry, see exactly why a recipe is ready or not, and prepare it one authored step at a time." headingLevel={1}>
      {isDemoMode ? <div className="demo-data-banner"><strong>Synthetic demo</strong><span>Recipe, pantry, history, and shopping edits stay in preview state and never write to production.</span></div> : null}
      {error ? <p className="error-copy" role="alert">{error}</p> : null}{message ? <p className="helper-copy" role="status">{message}</p> : null}

      <div className="drink-summary" aria-label="Drink preparation summary"><span><strong>{drinks.length}</strong> recipes</span><span><strong>{pantry.filter((item) => item.status === "available").length}</strong> available pantry items</span><span><strong>{stats.preparations}</strong> preparations</span><span><strong>{stats.uniqueDrinks}</strong> drinks made</span>{stats.mostMade ? <span><strong>{stats.mostMade.name}</strong> most made ({stats.mostMade.count})</span> : null}{stats.categoryMix.length ? <span><strong>{stats.categoryMix.map((entry) => drinkTypeLabels[entry.type as DrinkType] + " " + entry.count).join(" · ")}</strong> prepared type mix</span> : null}<span><strong>{stats.favoritePrepared}</strong> favorite recipes actually prepared</span>{stats.averageRating ? <span><strong>{stats.averageRating}</strong> saved rating average (n={stats.ratedCount})</span> : null}{stats.ratingTrend ? <span><strong>{stats.ratingTrend.delta > 0 ? "+" : ""}{stats.ratingTrend.delta}</strong> saved rating trend (recent n={stats.ratingTrend.windowSize} vs prior n={stats.ratingTrend.windowSize})</span> : stats.ratedCount ? <span><strong>n={stats.ratedCount}</strong> rating trend needs 4 rated preparations</span> : null}</div>

      <section className="drink-pantry" aria-labelledby="drink-pantry-title"><div><p className="eyebrow">Pantry evidence</p><h2 id="drink-pantry-title">What is actually on hand?</h2><p>Available and unavailable are explicit. Anything not listed stays unknown.</p></div><form onSubmit={handlePantryAdd}><label className="field-stack"><span>Ingredient</span><input required value={pantryName} onChange={(event) => setPantryName(event.target.value)} placeholder="Oat milk" /></label><label className="field-stack"><span>Status</span><select value={pantryStatus} onChange={(event) => setPantryStatus(event.target.value as typeof pantryStatus)}><option value="available">Available</option><option value="unavailable">Out / missing</option></select></label><button className="button-primary compact-button">Add to pantry</button></form><div className="pantry-chip-list">{pantry.map((item) => <span className="pantry-chip-group" key={item.id}><button type="button" className={"pantry-chip is-" + item.status} aria-label={item.name + ", " + item.status + ". Change status."} onClick={() => void savePantryItem(item.id, { name: item.name, note: item.note, status: item.status === "available" ? "unavailable" : "available" })}><strong>{item.name}</strong><small>{item.status === "available" ? "Available" : "Out / missing"}</small></button><button type="button" className="ghost-button compact-button" aria-label={"Remove " + item.name + " from pantry evidence"} onClick={() => void removePantryItem(item.id)}>Remove</button></span>)}</div></section>

      <section className="drink-library" aria-labelledby="make-now-title"><div className="drink-library-heading"><div><p className="eyebrow">Pantry match</p><h2 id="make-now-title">What can I make?</h2></div><Link className="button-primary compact-button" to={withReviewMode("/app/easydrinks/new", location.search)}>New recipe</Link></div><div className="drink-match-tabs" role="group" aria-label="Pantry match filters"><button type="button" aria-pressed={matchTier === "all"} onClick={() => setMatchTier("all")}>All recipes</button><button type="button" aria-pressed={matchTier === "ready"} onClick={() => setMatchTier("ready")}>Ready now</button><button type="button" aria-pressed={matchTier === "almost"} onClick={() => setMatchTier("almost")}>Missing only 1–2</button></div>
        <div className="drink-card-grid">{matches.map((match) => { const shopping = shoppingIngredients(match); return <article className={`drink-card drink-match-${match.tier}`} key={match.drink.id}><div className="drink-card-top"><span className="chip-pill">{match.tier === "ready" ? "Ready now" : match.tier === "almost" ? "Almost" : "Explore"}</span><span>{Math.round(match.coverage * 100)}% known available</span></div><div><h3><Link to={withReviewMode(`/app/easydrinks/${encodeURIComponent(match.drink.id)}`, location.search)}>{match.drink.name}</Link></h3><p>{drinkTypeLabels[match.drink.type]} · makes {match.drink.baseServings}</p></div><ul className="drink-match-evidence">{match.available.length ? <li><strong>Available:</strong> {match.available.map((item) => item.ingredient.name).join(", ")}</li> : null}{match.missing.length ? <li><strong>Out / missing:</strong> {match.missing.map((item) => item.ingredient.name).join(", ")}</li> : null}{match.unknown.length ? <li><strong>Unknown:</strong> {match.unknown.map((item) => item.ingredient.name).join(", ")}</li> : null}{match.optional.length ? <li><strong>Optional:</strong> {match.optional.map((item) => item.ingredient.name).join(", ")}</li> : null}</ul><div className="button-row"><Link className="button-primary compact-button" to={withReviewMode(`/app/easydrinks/${encodeURIComponent(match.drink.id)}/prepare`, location.search)}>Prepare</Link>{shopping.length ? <button type="button" className="button-secondary compact-button" onClick={() => { if (!window.confirm(`Create one Inbox shopping task for ${shopping.map((item) => item.name).join(", ")}?`)) return; void sendToShopping(match.drink, shopping).then(() => setMessage(isDemoMode ? "Synthetic shopping handoff confirmed; production was not changed." : "Shopping task created in Inbox with recipe provenance."), (nextError) => setMessage(nextError instanceof Error ? nextError.message : "Shopping handoff failed.")); }}>Send {shopping.length} to shopping</button> : null}</div></article>; })}</div>
      </section>

      <section className="drink-quick-capture" aria-labelledby="quick-drink-title"><div><p className="eyebrow">Fast capture</p><h2 id="quick-drink-title">Save the drink now</h2><p>Start with the essentials. Structured ingredients and preparation steps can come next.</p></div><form onSubmit={handleQuickCapture}><label className="field-stack"><span>Name</span><input required value={quickDraft.name} onChange={(event) => setQuickDraft({ ...quickDraft, name: event.target.value })} placeholder="What did you make?" /></label><label className="field-stack"><span>Type</span><select value={quickDraft.type} onChange={(event) => setQuickDraft({ ...quickDraft, type: event.target.value as DrinkType })}>{drinkTypes.map((entry) => <option key={entry} value={entry}>{drinkTypeLabels[entry]}</option>)}</select></label><label className="field-stack"><span>Date</span><input type="date" value={quickDraft.date} onChange={(event) => setQuickDraft({ ...quickDraft, date: event.target.value })} /></label><button className="button-primary">Save drink</button></form></section>

      <section className="drink-library" aria-labelledby="drink-library-title"><div className="drink-library-heading"><div><p className="eyebrow">Library</p><h2 id="drink-library-title">Saved recipes</h2></div></div><div className="drink-filters"><label className="field-stack drink-search"><span>Search</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, ingredient, step, note, or tag" /></label><label className="field-stack"><span>Type</span><select value={type} onChange={(event) => setType(event.target.value as DrinkType | "all")}><option value="all">All types</option>{drinkTypes.map((entry) => <option key={entry} value={entry}>{drinkTypeLabels[entry]}</option>)}</select></label><label className="field-stack"><span>Rating</span><select value={minimumRating} onChange={(event) => setMinimumRating(Number(event.target.value))}><option value={0}>Any rating</option><option value={3}>3+ stars</option><option value={4}>4+ stars</option><option value={5}>5 stars</option></select></label><label className="drink-filter-check"><input type="checkbox" checked={favoritesOnly} onChange={(event) => setFavoritesOnly(event.target.checked)} /> Favorites only</label></div>{isLoading ? <div className="empty-state" role="status"><strong>Loading private drink data…</strong></div> : null}<div className="drink-card-grid">{filtered.map((drink) => <article className="drink-card" key={drink.id}><div className="drink-card-top"><span className="chip-pill">{drinkTypeLabels[drink.type]}</span><button type="button" className="favorite-button" aria-label={drink.favorite ? `Remove ${drink.name} from favorites` : `Add ${drink.name} to favorites`} aria-pressed={drink.favorite} onClick={() => void saveDrink(drink.id, { ...drink, favorite: !drink.favorite })}>{drink.favorite ? "★" : "☆"}</button></div><div><h3><Link to={withReviewMode(`/app/easydrinks/${encodeURIComponent(drink.id)}`, location.search)}>{drink.name}</Link></h3><p>{drink.ingredients.length} ingredients · {drink.steps.length} steps · {drink.date}</p></div><div className="drink-card-bottom"><span>{drink.rating ? `${"★".repeat(drink.rating)}${"☆".repeat(5 - drink.rating)}` : "Not rated"}</span><button type="button" className="ghost-button compact-button" onClick={() => void copyDrink(drink).then(() => setMessage("A copy was saved with today's date."))}>Duplicate</button></div></article>)}</div></section>

      <section className="drink-library" aria-labelledby="prep-history-title"><div><p className="eyebrow">Preparation history</p><h2 id="prep-history-title">Recent makes</h2></div>{!preparations.length ? <div className="empty-state"><strong>No preparations logged yet.</strong><p>Finishing guided preparation creates the first private history record.</p></div> : <div className="drink-history-list">{preparations.slice(0, 8).map((record, index) => <article key={record.id}><div><strong>{record.drinkName}</strong><p>{record.servings} serving{record.servings === 1 ? "" : "s"} · {record.preparedAt?.toLocaleString() || "Pending sync"}</p></div>{index === 0 ? <button type="button" className="ghost-button compact-button" onClick={() => void undoPreparation(record.id).then(() => setMessage("Latest preparation log undone; the recipe was not changed."))}>Undo latest log</button> : null}</article>)}</div>}</section>
    </PageSection>
  );
}
