import { DRINK_SCHEMA_VERSION, type DrinkRecord } from "@/lib/firestore/drinks";

export const drinkDemoFixtures: DrinkRecord[] = [
  {
    id: "demo-oat-latte",
    ownerId: "local-preview",
    schemaVersion: DRINK_SCHEMA_VERSION,
    name: "Maple oat latte",
    type: "coffee",
    ingredients: [
      { name: "Espresso", amount: "2", unit: "shots" },
      { name: "Oat milk", amount: "8", unit: "oz" },
      { name: "Maple syrup", amount: "1", unit: "tsp" },
    ],
    instructions: "Warm the oat milk, combine, and stir gently.",
    notes: "Comforting without being too sweet.",
    rating: 5,
    tags: ["morning", "warm"],
    date: "2026-08-08",
    favorite: true,
    sourceDrinkId: null,
    createdAt: new Date("2026-08-08T14:00:00Z"),
    updatedAt: new Date("2026-08-08T14:00:00Z"),
  },
  {
    id: "demo-citrus-sparkler",
    ownerId: "local-preview",
    schemaVersion: DRINK_SCHEMA_VERSION,
    name: "Citrus garden sparkler",
    type: "mocktail",
    ingredients: [
      { name: "Sparkling water", amount: "6", unit: "oz" },
      { name: "Orange juice", amount: "2", unit: "oz" },
      { name: "Mint", amount: "4", unit: "leaves" },
    ],
    instructions: "Build over ice and stir once.",
    notes: "Bright and simple.",
    rating: 4,
    tags: ["citrus", "cold"],
    date: "2026-08-07",
    favorite: false,
    sourceDrinkId: null,
    createdAt: new Date("2026-08-07T20:00:00Z"),
    updatedAt: new Date("2026-08-07T20:00:00Z"),
  },
  {
    id: "demo-berry-shake",
    ownerId: "local-preview",
    schemaVersion: DRINK_SCHEMA_VERSION,
    name: "Berry recovery shake",
    type: "protein-shake",
    ingredients: [
      { name: "Frozen berries", amount: "1", unit: "cup" },
      { name: "Protein powder", amount: "1", unit: "scoop" },
      { name: "Milk or alternative", amount: "8", unit: "oz" },
    ],
    instructions: "Blend until smooth.",
    notes: "Add more liquid for a lighter texture.",
    rating: 4,
    tags: ["post-workout", "quick"],
    date: "2026-08-05",
    favorite: true,
    sourceDrinkId: null,
    createdAt: new Date("2026-08-05T22:00:00Z"),
    updatedAt: new Date("2026-08-05T22:00:00Z"),
  },
];
