import { createGameSessionId, EASYGAMES_GENERATOR_VERSION, type GameDifficulty, type GameMode } from "./gameContracts.ts";

export const TRAIL_SCOUT_VERSION = 2;
type TrailBoard = { size: number; rocks: number[]; goals: number[]; moves: number; };
const trailBoards: Record<GameDifficulty, TrailBoard[]> = {
  easy: [{ size: 5, rocks: [6, 8], goals: [4, 24], moves: 32 }, { size: 5, rocks: [7, 13], goals: [20, 24], moves: 32 }],
  standard: [{ size: 5, rocks: [6, 8, 16, 18], goals: [4, 20, 24], moves: 28 }, { size: 5, rocks: [2, 7, 11, 17], goals: [9, 20, 24], moves: 28 }, { size: 5, rocks: [5, 8, 13, 16], goals: [4, 19, 22], moves: 28 }],
  hard: [{ size: 6, rocks: [7, 8, 10, 13, 16, 19, 22, 25, 26], goals: [5, 17, 30, 35], moves: 32 }, { size: 6, rocks: [7, 9, 13, 15, 20, 22, 26, 28], goals: [5, 23, 30, 35], moves: 32 }],
};

export type TrailDirection = "up" | "right" | "down" | "left";
export type TrailScoutState = { version: typeof TRAIL_SCOUT_VERSION; generatorVersion: typeof EASYGAMES_GENERATOR_VERSION; difficulty: GameDifficulty; mode: GameMode; dateKey: string | null; challengeKey: string | null; seed: number; sessionId: string; startedAt: string; updatedAt: string; revision: number; size: number; rocks: number[]; initialGoals: number[]; goals: number[]; totalGoals: number; player: number; movesRemaining: number; moves: number; collected: number; status: "playing" | "paused" | "won" | "lost"; };
function advanced(state: TrailScoutState, updates: Partial<TrailScoutState>): TrailScoutState { return { ...state, ...updates, revision: state.revision + 1, updatedAt: new Date().toISOString() }; }
export function createTrailScout(seed = Date.now(), options: Partial<Pick<TrailScoutState, "difficulty" | "mode" | "dateKey" | "challengeKey" | "sessionId" | "startedAt">> = {}): TrailScoutState { const difficulty = options.difficulty || "standard"; const mode = options.mode || "free"; const startedAt = options.startedAt || new Date().toISOString(); const boards = trailBoards[difficulty]; const board = boards[(seed >>> 0) % boards.length]; return { version: TRAIL_SCOUT_VERSION, generatorVersion: EASYGAMES_GENERATOR_VERSION, difficulty, mode, dateKey: options.dateKey || null, challengeKey: options.challengeKey || null, seed: seed >>> 0, sessionId: options.sessionId || createGameSessionId("trail-scout", mode, difficulty, seed), startedAt, updatedAt: startedAt, revision: 0, size: board.size, rocks: [...board.rocks], initialGoals: [...board.goals], goals: [...board.goals], totalGoals: board.goals.length, player: 0, movesRemaining: board.moves, moves: 0, collected: 0, status: "playing" }; }
export function moveTrailScout(state: TrailScoutState, direction: TrailDirection): TrailScoutState { if (state.status !== "playing") return state; const row = Math.floor(state.player / state.size); const column = state.player % state.size; const delta = direction === "up" ? [-1, 0] : direction === "right" ? [0, 1] : direction === "down" ? [1, 0] : [0, -1]; const nextRow = row + delta[0]; const nextColumn = column + delta[1]; if (nextRow < 0 || nextRow >= state.size || nextColumn < 0 || nextColumn >= state.size) return state; const player = nextRow * state.size + nextColumn; if (state.rocks.includes(player)) return state; const foundGoal = state.goals.includes(player); const goals = foundGoal ? state.goals.filter((goal) => goal !== player) : state.goals; const movesRemaining = state.movesRemaining - 1; return advanced(state, { player, goals, collected: state.collected + (foundGoal ? 1 : 0), movesRemaining, moves: state.moves + 1, status: goals.length === 0 ? "won" : movesRemaining <= 0 ? "lost" : "playing" }); }
export function pauseTrailScout(state: TrailScoutState) { return state.status === "playing" ? advanced(state, { status: "paused" }) : state.status === "paused" ? advanced(state, { status: "playing" }) : state; }
export function trailScoutScore(state: TrailScoutState) { const difficultyBonus = state.status === "won" ? { easy: 0, standard: 75, hard: 150 }[state.difficulty] : 0; return state.collected * 250 + (state.status === "won" ? state.movesRemaining * 20 + 250 : 0) + difficultyBonus; }
export function trailBoardSpecs() { return Object.entries(trailBoards).flatMap(([difficulty, boards]) => boards.map((board) => ({ difficulty: difficulty as GameDifficulty, ...board }))); }
export function isTrailScoutState(value: unknown): value is TrailScoutState { if (!value || typeof value !== "object") return false; const state = value as Partial<TrailScoutState>; const cells = Number(state.size) * Number(state.size); const validIndexes = (items: unknown) => Array.isArray(items) && items.every((index) => Number.isInteger(index) && Number(index) >= 0 && Number(index) < cells); return state.version === 2 && state.generatorVersion === EASYGAMES_GENERATOR_VERSION && ["easy", "standard", "hard"].includes(state.difficulty || "") && ["free", "daily"].includes(state.mode || "") && Number.isInteger(state.size) && state.size! >= 4 && state.size! <= 8 && validIndexes(state.rocks) && validIndexes(state.initialGoals) && validIndexes(state.goals) && Number.isInteger(state.totalGoals) && state.totalGoals! >= state.goals!.length && Number.isInteger(state.player) && state.player! >= 0 && state.player! < cells && !state.rocks!.includes(state.player!) && Number.isInteger(state.movesRemaining) && state.movesRemaining! >= 0 && state.movesRemaining! <= 100 && Number.isInteger(state.moves) && state.moves! >= 0 && Number.isInteger(state.collected) && state.collected! >= 0 && state.collected! + state.goals!.length === state.totalGoals && ["playing", "paused", "won", "lost"].includes(state.status || "") && typeof state.sessionId === "string" && state.sessionId.length >= 8 && Number.isInteger(state.revision) && state.revision! >= 0; }
